### Verbo GET – listar
GET http://localhost:8000/funcionario HTTP/1.1

### Verbo POST - adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
content-type : application/json

{
    "nome" : "Kauan",
    "matricula" : "11111",
    "cpf" : "22222",
    "telefone" : "3333",
    "grupo" : "4",
    "senha" : "55555"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type : application/json

{
    "nome" : "KAUAN2" ,
    "matricula" : "2" ,
    "cpf" : "3" ,
    "telefone" : "4" ,
    "grupo" : 5 ,
    "senha" : "6"
}

### Verbo DELL - atualiza
DELETE  http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type : application/json
